### ISSUE TITLE
Block Sound Event crash

### ISSUE THREAD

**Issue by plenet10** [SteveKunG/MorePlanets#26] opened 2018-03-25 19:41 UTC
I broke tall grass and it killed the client. just a note it could be something to do with other mods because i have more than 500 of them running.
if you need anything just say and i will try to add it for you.
[crash-2018-03-25_20.48.56-client.txt](https://github.com/SteveKunG/MorePlanets/files/1845712/crash-2018-03-25_20.48.56-client.txt)

**Comment by SteveKunG** [comment] 2018-04-07 21:39
I can't reproduce in my tests. Also Koentus Block still unobtainable in survival except Creative Mode.

**Comment by SteveKunG** [comment] 2018-05-13 15:50
Due to remove metadata from block, this should be fixed.

**Closed as completed by SteveKunG** 2018-05-13 15:50 UTC
Labels: Bug, 1.12.2, Fixed in Dev
