### ISSUE TITLE
Minecraft wont launch with 1.12.2-2.2.2-GC280 version

### ISSUE THREAD

**Issue by mMONTAGEe** [SteveKunG/MorePlanets#133] opened 2022-01-15 07:00 UTC
Attempting to launch Minecraft with Moreplanets 1.12.2-2.2.2-GC280  SteveKunG lib and mixinbooster, After i press launch the minecraft won't launch, Exit code 0 without crashlog, Only latest.log

https://pastebin.com/vBpHrhgB

**Comment by SteveKunG** [comment] 2022-01-15 07:19
Duplicate of #132

**Closed as completed by SteveKunG** 2022-01-15 07:19 UTC
Labels: 1.12.2
