### ISSUE TITLE
Sound issues in Multiplayer

### ISSUE THREAD

**Issue by Manwil00** [SteveKunG/MorePlanets#71] opened 2019-10-07 14:18 UTC
More-Planets-1.12.2-2.0.21
Sounds of mobs added by the mod fail playing while being on a Multiplayer Server.
The following Report was generated after coming across a Cheese Floated but the same thing also happened with Alien Miners.

Notification by VanillaFix : https://paste.dimdev.org/xadagarema.mccrash

**Comment by SteveKunG** [comment] 2019-11-08 05:21
Seems work fine to me, Cannot reproduce. (Multiplayer test)

![2019-11-08_12 20 39](https://user-images.githubusercontent.com/6128413/68451670-389a4780-0222-11ea-92e7-72dca32114af.png)

**Comment by ThexXTURBOXx** [comment] 2019-11-08 06:13
I have had the Same issue, will investigate further later on.
But I think, it's because you check in your registerSounds() method, whether you are on a client, which doesn't make sense, because you have to register the sounds on the server as well.
If you don't register them on the Server, it can't resolve the Sound ID and then wrong packets get sent to the Client (specifically the Packet, which plays Vanilla Sounds). But because your Sounds aren't Vanilla Sounds - obviously - VanillaFix Shows the notification

**Comment by SteveKunG** [comment] 2019-11-08 11:48
Oops, it seems missing RegistryEvent for SoundEvent.

**Comment by SteveKunG** [comment] 2019-11-08 17:09
Fixed on both versions. 2.1.9 and 2.0.22.

**Closed as completed by SteveKunG** 2019-11-08 17:09 UTC
Labels: Bug, Fixed, 1.12.2, Priority
